package com.kotlincrossplatform.tasksfaculdade.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Theme ──────────────────────────────────────────────────────────────
val LightBackground            = Color(0xFFF0F7F7)
val LightOnBackground          = Color(0xFF1A2E2E)
val LightSurface               = Color(0xFFFFFFFF)
val LightOnSurface             = Color(0xFF1A2E2E)
val LightSurfaceVariant        = Color(0xFFE0F2F1)
val LightOnSurfaceVariant      = Color(0xFF37474F)
val LightPrimary               = Color(0xFF00897B)
val LightOnPrimary             = Color(0xFFFFFFFF)
val LightPrimaryContainer      = Color(0xFFB2DFDB)
val LightOnPrimaryContainer    = Color(0xFF004D40)
val LightSecondary             = Color(0xFF0097A7)
val LightOnSecondary           = Color(0xFFFFFFFF)
val LightSecondaryContainer    = Color(0xFFB2EBF2)
val LightOnSecondaryContainer  = Color(0xFF006064)
val LightTertiary              = Color(0xFF00838F)
val LightOnTertiary            = Color(0xFFFFFFFF)
val LightTertiaryContainer     = Color(0xFFE0F7FA)
val LightOnTertiaryContainer   = Color(0xFF006064)
val LightError                 = Color(0xFFD32F2F)
val LightOnError               = Color(0xFFFFFFFF)
val LightErrorContainer        = Color(0xFFFFCDD2)
val LightOnErrorContainer      = Color(0xFFB71C1C)
val LightOutline               = Color(0xFF80CBC4)
val LightOutlineVariant        = Color(0xFFB2DFDB)
val LightScrim                 = Color(0xFF000000)

// ── Dark Theme ────────────────────────────────────────────────────────────────
val DarkBackground             = Color(0xFF0D1B2A)
val DarkOnBackground           = Color(0xFFE0F2F1)
val DarkSurface                = Color(0xFF102232)
val DarkOnSurface              = Color(0xFFE0F2F1)
val DarkSurfaceVariant         = Color(0xFF1A3044)
val DarkOnSurfaceVariant       = Color(0xFF80CBC4)
val DarkPrimary                = Color(0xFF80CBC4)
val DarkOnPrimary              = Color(0xFF003733)
val DarkPrimaryContainer       = Color(0xFF00574F)
val DarkOnPrimaryContainer     = Color(0xFFB2DFDB)
val DarkSecondary              = Color(0xFF80DEEA)
val DarkOnSecondary            = Color(0xFF003E47)
val DarkSecondaryContainer     = Color(0xFF00626E)
val DarkOnSecondaryContainer   = Color(0xFFB2EBF2)
val DarkTertiary               = Color(0xFF00E5FF)
val DarkOnTertiary             = Color(0xFF003640)
val DarkTertiaryContainer      = Color(0xFF004E5A)
val DarkOnTertiaryContainer    = Color(0xFFB2EBF2)
val DarkError                  = Color(0xFFEF9A9A)
val DarkOnError                = Color(0xFF6F0000)
val DarkErrorContainer         = Color(0xFFB71C1C)
val DarkOnErrorContainer       = Color(0xFFFFCDD2)
val DarkOutline                = Color(0xFF4DB6AC)
val DarkOutlineVariant         = Color(0xFF1A3044)
val DarkScrim                  = Color(0xFF000000)
